config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "videos#index"

  get 'search' => 'application#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/navigable.rb
module Navigable
    extend ActiveSupport::Concern

    def next
        self.class.where("id > ?", self.id).order(id: :asc).first
    end

    def previous
        self.class.where("id < ?", self.id).order(id: :desc).first
    end
end

app/models/person.rb
class Person < ActiveOrient::V

end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  pay_customer
end

app/models/video.rb
class Video < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include Navigable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end

  def search
    #Video.__elasticsearch__.create_index!
    s_search = params[:search]
    #@objects = Video.search(s_search).records
    @objects = Elasticsearch::Model.search(s_search, [], size: 100)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @name = Person.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all.order(published_at: :desc).limit(100)
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:name, :title, :youtube_id, :transcription)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/application/search.html.erb
<%@objects.each do |item|%>
<div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <div class="col-auto d-none d-lg-block">
    <img src="https://img.youtube.com/vi/<%=item.youtube_id%>/0.jpg">
  </div>

  <div class="col p-4 d-flex flex-column position-static">
    <strong class="d-inline-block mb-2 text-primary">COTV</strong><%=fa_icon "camera-retro"%>
    <h3 class="mb-0"><%=link_to(item.title, "/videos/#{item.id}")%></h3>
    <div class="mb-1 text-muted"> <%=item.published_at%> </div>
    <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
  </div>

</div>


  <br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcoIndex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="#" class="nav-link text-secondary">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"/></svg>
                Home
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"/></svg>
                Dashboard
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"/></svg>
                Orders
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"/></svg>
                Products
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"/></svg>
                Customers
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" action="/search" method='get'>
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="search">
          <input type="submit">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-light text-dark me-2">Login</button>
          <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

  <main><div class="container">
    <%= yield %>
  </div></main>

  </body>
</html>

app/views/pay/payments/show.html.erb
<div
  data-controller="payment-intent"
  data-payment-intent-client-secret-value="<%= @payment.client_secret %>"
  data-payment-intent-status-value="<%= @payment.status %>"
  data-payment-intent-customer-value="<%= @payment.customer %>"
  class="h-screen md:flex md:justify-center md:items-center">
  <div class="w-full max-w-lg">
    <!-- Status Messages -->
    <p data-payment-intent-target="error" class="hidden items-center mb-4 bg-red-100 border border-red-200 px-5 py-2 rounded-lg text-red-500">
      <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 text-red-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>

      <span data-payment-intent-target="errorMessage" class="ml-3"></span>
    </p>

    <p data-payment-intent-target="success" class="hidden items-center mb-4 bg-green-100 border border-green-200 px-5 py-4 rounded-lg text-green-700">
      <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 text-green-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
      </svg>

      <span data-payment-intent-target="successMessage" class="ml-3"></span>
    </p>

    <div class="bg-white rounded-lg shadow-xl p-4 sm:py-6 sm:px-10 mb-5">
      <% if @payment.succeeded? %>
        <h1 class="text-xl mt-2 mb-4 text-gray-700"><%=t "pay.successful.header" %></h1>
        <p class="mb-6"><%=t "pay.successful.description" %></p>

      <% elsif @payment.canceled? %>
        <h1 class="text-xl mt-2 mb-4 text-gray-700"><%=t "pay.cancelled.header" %></h1>
        <p class="mb-6"><%=t "pay.cancelled.description" %></p>

      <% else %>
        <div data-payment-intent-target="form" id="payment-elements">
          <!-- Instructions -->
          <h1 class="text-xl mt-2 mb-4 text-gray-700"><%=t "pay.requires_action.header", amount: @payment.amount_with_currency %></h1>
          <p class="mb-6"><%=t "pay.requires_action.description" %></p>

          <div data-payment-intent-target="cardFields" class="hidden">
            <!-- Name -->
            <label for="cardholder-name" class="inline-block text-sm text-gray-700 font-semibold mb-2"><%=t "pay.requires_action.full_name" %></label>
            <input data-payment-intent-target="name" id="cardholder-name" type="text" placeholder="Jane Doe" required autofocus class="mt-1 mb-6 block w-full px-3 py-2 rounded-md border border-gray-300 shadow-sm focus:outline-none focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50">

            <!-- Card -->
            <label for="card-element" class="inline-block text-sm text-gray-700 font-semibold mb-2"><%=t "pay.requires_action.card" %></label>
            <div data-payment-intent-target="card" id="card-element" class="mt-1 mb-6 block w-full px-3 py-4 rounded-md border border-gray-300 shadow-sm focus:outline-none focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"></div>
          </div>

          <!-- Pay Button -->
          <button data-payment-intent-target="button" data-action="click->payment-intent#confirmPayment" class="inline-block w-full px-4 py-3 mb-4 text-white rounded-lg bg-blue-400 hover:bg-blue-500">
            <%=t "pay.requires_action.button", amount: @payment.amount_with_currency %>
          </button>
        </div>
      <% end %>

      <%= link_to t("pay.back"), @redirect_to, class: "inline-block w-full px-4 py-3 bg-gray-100 hover:bg-gray-200 text-center text-gray-600 rounded-lg" %>
    </div>

    <p class="text-center text-gray-500 text-sm">
      © <%= Date.current.year %> <%= Pay.business_name %> <%=t "pay.all_rights_reserved" %>
    </p>
  </div>
</div>

<script type="module">
  window.stripe = Stripe('<%= Pay::Stripe.public_key %>');

  import { Application, Controller } from 'https://cdn.skypack.dev/@hotwired/stimulus'
  const application = Application.start()

  application.register('payment-intent', class extends Controller {
    static targets = ["error", "errorMessage", "success", "successMessage", "form", "button", "name", "card", "cardFields"]
    static values = {
      clientSecret: String,
      customer: String,
      status: String,
      errorMessage: String,
      successMessage: String,
      complete: Boolean,
      processing: Boolean
    }

    connect() {
      if (this.hasCardTarget) {
        this.elements = stripe.elements()
        this.cardElement = this.elements.create("card")
        this.cardElement.mount(this.cardTarget)
      }
    }

    statusValueChanged() {
      switch(this.statusValue) {
        case "requires_action":
          stripe.confirmCardPayment(this.clientSecretValue).then(this.handleConfirmResult.bind(this))
          break;
        case "requires_payment_method":
          this.cardFieldsTarget.classList.toggle("hidden", false)
          break;
      }
    }

    confirmPayment() {
      this.processingValue = true
      this.completeValue = false
      stripe.confirmCardPayment(this.clientSecretValue, {
        payment_method: {
          card: this.cardElement,
          billing_details: { name: this.nameTarget.value }
        },
        save_payment_method: this.customerValue != "",
        setup_future_usage: 'off_session',
      }).then(this.handleConfirmResult.bind(this))
    }

    handleConfirmResult(result) {
      this.processingValue = false

      if (result.error) {
        if (result.error.code === 'parameter_invalid_empty' &&
          result.error.param === 'payment_method_data[billing_details][name]') {
          this.errorMessageValue = '<%=t "pay.requires_action.name_missing" %>'
        } else {
          this.errorMessageValue = result.error.message
          this.statusValue = result.error.payment_intent.status
        }
      } else {
        this.completeValue = true;
        this.successMessageValue = '<%=t "pay.requires_action.success" %>'
      }
    }

    completeValueChanged() {
      if (this.hasFormTarget) {
        this.formTarget.classList.toggle("hidden", this.completeValue)
      }
    }

    processingValueChanged() {
      if (this.hasButtonTarget) {
        this.buttonTarget.disabled = this.processingValue
        this.buttonTarget.classList.toggle("bg-blue-400", this.processingValue)
        this.buttonTarget.classList.toggle("bg-blue-500", !this.processingValue)
      }
    }

    errorMessageValueChanged() {
      this.errorMessageTarget.textContent = this.errorMessageValue
      const enabled = (this.errorMessageValue != '')
      this.errorTarget.classList.toggle("flex", enabled)
      this.errorTarget.classList.toggle("hidden", !enabled)
    }

    successMessageValueChanged() {
      this.successMessageTarget.textContent = this.successMessageValue
      const enabled = (this.successMessageValue != '')
      this.successTarget.classList.toggle("flex", enabled)
      this.successTarget.classList.toggle("hidden", !enabled)
    }
  })
</script>

app/views/pay/stripe/_checkout_button.html.erb
<%= button_tag title,
  id: "checkout-#{session.id}",
  class: local_assigns[:class],
  style: (local_assigns[:class] || local_assigns[:style]) ? local_assigns[:style] : 'background-color:#6772E5;color:#FFF;padding:8px 12px;border:0;border-radius:4px;font-size:1em'
%>
<%= tag.div id: "error-for-#{session.id}" %>

<script>
  (() => {
    const checkoutButton = document.getElementById("checkout-<%= session.id %>");
    checkoutButton.addEventListener('click', function () {
      Stripe("<%= Pay::Stripe.public_key %>").redirectToCheckout({
        sessionId: '<%= session.id %>'
      }).then(function (result) {
        if (result.error) {
            document.getElementById("error-for-#{session.id}").innerText = result.error.message;
          }
      });
    });
  })()
</script>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Name:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :youtube_id, style: "display: block" %>
    <%= form.text_field :youtube_id %>
  </div>

  <div>
    <%= form.label :transcription, style: "display: block" %>
    <%= form.text_area :transcription %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
    <li>
        <ul><%=link_to "#{video.published_at} - #{video.title}", video%></ul>
    </li>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Show this video", @video %> |
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Videos</h1>

<div id="videos">
  <% @videos.each do |video| %>
    <%= render video %>
  <% end %>
</div>

<%= link_to "New video", new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">

<!--
<iframe width="560" height="315" src="https://www.youtube.com/embed/<%=@video.youtube_id%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
-->
<video width="640" height="360" controls>
 <source src="/cotv/<%=@video.youtube_id%>.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>



<h1><%=@video.title%></h1>

<%=@video.youtube_id%><br>

<%=@video.transcription%>

<div>
  <%= link_to "Edit this video", edit_video_path(@video) %> |
  <%= link_to "Back to videos", videos_path %>

  <%= button_to "Destroy this video", @video, method: :delete %>
</div>